### ISSUE TITLE
Wrong dates are getting disabled when the local time zone(system time) is set to EST.

### ISSUE THREAD

**Issue by onewhocodes** [najlepsiwebdesigner/foundation-datepicker#102]
Hi Peter,

Thanks for the datepicker!

I'm trying to disable the previous dates in the calendar. So I've put this code. Please check the image attached(for better understanding).

var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
var checkin = $('#dpd1').fdatepicker({
    onRender: function (date) {
    console.log(date+'---'+now+'---'+date.valueOf()+'-<-'+now.valueOf()+'---'+(date.valueOf() <     now.valueOf()));
    return date.valueOf() < now.valueOf() ? 'disabled' : '';
}
}).data('datepicker');

It works great for time zone IST, but disables today's date for time zone EST.
![datepicker-issue](https://cloud.githubusercontent.com/assets/13976808/9759928/5e6526ea-56b6-11e5-9fcc-4391031d4f38.png)

**Comment by onewhocodes** [comment]
Could you please help me on this?

**Comment by najlepsiwebdesigner** [comment]
:D 
http://www.worldtimebuddy.com/est-to-ist-converter

notice the absolute difference between EST and IST, you'll get your answer

**Comment by onewhocodes** [comment]
Hi Peter,

Thanks for the reply :)

Yes there's 10.30 hrs difference between IST and EST. When it's 12.30pm in IST, it's 2am in EST. But the date will be same right September 10, 2015(You may be laughing at me now :smile: ).

Could you please help me understand this? Is there anything I need to do to not disable present date(When it's EST)?
![datepicker-issue](https://cloud.githubusercontent.com/assets/13976808/9783043/5e45d2b6-5767-11e5-8925-35147389b91e.png)


Thanks.

**Comment by onewhocodes** [comment]
Oops I get it! Thanks.
