### ISSUE TITLE
Local time

### ISSUE THREAD

**Issue by stroborobo** [najlepsiwebdesigner/foundation-datepicker#107]
There's `date` and `viewDate`, why?

I noticed that because `update()` sets them and [`DPGlobal.parseDate()` returns a date instance that is not equal to the one you pass in](https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/bf5c8f4/js/foundation-datepicker.js#L1274). So if I have two dependent pickers (including time display) and call `update()` with an offset of one hour, what I get is event.date + 1 hour + TZ offset.

**Comment by Knorkebrot** [comment]
Why does it handle UTC anyways? Shouldn't I be able to select my locale time from the picker?
