### ISSUE TITLE
not working on meteor

### ISSUE THREAD

**Issue by Fattouh92** [najlepsiwebdesigner/foundation-datepicker#109]
i have the js code in client/compatibility and the css in client/stylesheets, i copied the code from example page to linking two datepickers and calling it in my Template.onRendered(). calling fdatepicker() doesnt give undefined function but nothing is working

**Comment by najlepsiwebdesigner** [comment]
Can you create a fiddle or share an example? I cannot help you with debugging without sources. Is there anything in the console?

Odoslané z iPhonu

Dňa 3. 11. 2015, o 8:43, Mohamed Tamer Abul Azm <notifications@github.com> napísal:
