### ISSUE TITLE
AM/PM non-military time.

### ISSUE THREAD

**Issue by djvinny** [najlepsiwebdesigner/foundation-datepicker#111]
Can this be implemented, even though I understand the military time concept, there are quite a lot of people who still do not and prefer a non 24 hour clock.

**Comment by smartpill** [comment]
I was going to ask the same.

**Comment by najlepsiwebdesigner** [comment]
Hi. Thanks for your feedback. I do not have plans for implementing this in following versions, but I'll gladly accept pull request.

**Comment by CRiva** [comment]
I am actually manually editing the js/css to have an ampm format. I'd be happy to pull request if you'd like it?

**Comment by ahemphill99** [comment]
Id really like to know how this is done? Im using the time selector here nosh.co.nz

**Comment by CRiva** [comment]
https://github.com/najlepsiwebdesigner/foundation-datepicker/pull/211 

Here's the link to my pull request so you can see the changes I made. I have actually edited it further so non-military time can be used for both selecting and filling in, and as described above. I just haven't updated the repo yet.

**Comment by CRiva** [comment]
@najlepsiwebdesigner Just following up on this, I've had a PR open for a couple months now, if you cared to look at it.
