### ISSUE TITLE
Can't select a date (month and year) without selecting a day

### ISSUE THREAD

**Issue by rspt** [najlepsiwebdesigner/foundation-datepicker#112]
I want to display a month calendar when a user can simply pickup a month.

Here's my code:
```  
$('#date').fdatepicker({
    format: 'mm/yyyy',
    startView: 3,
    minView: 3
  });
```

**Comment by Cethy** [comment]
+1
It's kinda broken too on the example page.

**Comment by rspt** [comment]
Will try asap. Thanks anyway for working on it!
