### ISSUE TITLE
FontAwsome and Foundation Icons don't work together

### ISSUE THREAD

**Issue by jondor** [najlepsiwebdesigner/foundation-datepicker#113]
As I need both font awesome AND foundation Icons and have both loaded I run into an issue that they interfere and no arrow is shown at all..

**Comment by najlepsiwebdesigner** [comment]
Hi!

You should change arrow classes in html template defined in
foundation-datepicker.js file (at the bottom). Just remove the ones you
dont need, it will stop interfering.


Dňa piatok, 20. novembra 2015 jondor <notifications@github.com> napísal(a):

> As I need both font awesome AND foundation Icons and have both loaded I
> run into an issue that they interfere and no arrow is shown at all..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/najlepsiwebdesigner/foundation-datepicker/issues/113>.
>


-- 

Ing. Peter Beňo
--------------------------------
Web development & computer vision
http://about.me/peterbeno

**Comment by jondor** [comment]
I also just saw there's a version without font-awesome.. Just a matter of reading better.. Excuses and thanks!

**Comment by najlepsiwebdesigner** [comment]
Version without font-awesome is *old* - just warning.

Ing. Peter Beňo
--------------------------------
Web development & computer vision
http://about.me/peterbeno
