### ISSUE TITLE
How to use this instead of default scaffold form?

### ISSUE THREAD

**Issue by dhokes** [najlepsiwebdesigner/foundation-datepicker#116]
Using Foundation on a rails site and scaffolding on a Model with a datetime type e.g. dob in the example below, the view generates the following code:

```rails
<div class="field">
    <%= f.label :dob %><br>
    <%= f.datetime_select :dob %>
</div>
```
This displays five drop down lists like this - http://i.stack.imgur.com/L5bTs.png

So instead of these, I'm trying to use this datetime picker.

My code includes the following:

```rails
<%= form_for(@note) do |f| %>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :class => 'datetimepicker' %>
  </div>

  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.select(:company_id, Company.order("name").map { |s| [s.name, s.id] }) %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <%= link_to "home", root_path, { :class=>"button expand" } %>

  <script type="text/javascript">
    $(document).ready(function() {
      $('.datetimepicker').fdatetimepicker();
    });
  </script>
<% end %>
```

Is this how you intend this to be used?

My issue is that the datepicker functions correctly but it is sitting on top of other elements, specifically the company_id label from the code above and it's not 'inline'.  It looks like this - http://i.stack.imgur.com/2NrvA.png

**Comment by najlepsiwebdesigner** [comment]
Hello! You are probably using fdateTIMEpicker which is not supported anymore and was merged into this repository. Please use JS and CSS files of foundation-datepicker (this repository) and initialize with .fdatepicker() and it should work correctly.
