### ISSUE TITLE
Calendar doesn't close on click date in modal (IE only)

### ISSUE THREAD

**Issue by wim-mertens** [najlepsiwebdesigner/foundation-datepicker#124]
When I add the datepicker in a reveal-modal, I've got an issue in IE11. On selecting the date, the calendar doesn't close. Only by clicking outside it will close. In other browsers it works fine.

**Comment by koolfreak** [comment]
my issue is the datepicker is not showing on the reveal modal? how do you display this datepicker on modal window? any code sample?
Thanks

**Comment by wim-mertens** [comment]
Hi, a sample can be found here: http://www.farbeyond.co.nz/daterange/

Cheers

**Comment by najlepsiwebdesigner** [comment]
Hi!

It works for me on Safari and Chrome on mac, can you please describe the
platform you are using?

Maybe I will be able to help you.

Thanks


Ing. Peter Beňo
--------------------------------
Web development & computer vision & robotics
http://peterbeno.com

**Comment by wim-mertens** [comment]
Hi, I am using Windows 7, testing in IE 11. Other browsers work fine. Strangely enough it works on this quick sample page I set up, but it doesn't work on my project page. Can't post that link unfortunately as the site's not live yet. Can I pm you?

Thanks,
Wim

**Comment by najlepsiwebdesigner** [comment]
Hi,

I'm sorry but currently I don't have a time to debug your solution, I'm
totally busy. However, I will give you few ideas:

- if there is no error in browser console, try to check, if the datepicker
html code was successfully appended to source of your page - that would
mean that you are just not handling the click on the datepicker, but it is
initialized correctly
- if the datepicker is here, make sure you are actually clicking on the
element which should handle the datepicker. There is some possibility that
you just covered the element with something, check zindexes
- check zindexes of datepicker vs zindexes of the reveal modal



Ing. Peter Beňo
--------------------------------
Web development & computer vision & robotics
http://peterbeno.com

**Comment by wim-mertens** [comment]
Hi Peter,

I understand, no problem. Thanks heaps for the advice though. It's not such a big issue, I'll figure it out :) I'll post an update here if I do.

Cheers,
Wim

**Comment by koolfreak** [comment]
Hi Peter,

I already figured it out. thanks
