### ISSUE TITLE
z-index problem

### ISSUE THREAD

**Issue by lgallois** [najlepsiwebdesigner/foundation-datepicker#132]
Hello!

I had a problem with z-index and because of that, the calendar didn't show up. I've already fix this problem on my code, just to report. :)
Thanks!

**Comment by danki** [comment]
Same here, the z-index set is at 10xx and wont appear, think the zindex should definitely be dynamic via options or something. Using _Jedi-powers_ with **!important** will do the trick but personally i hate using !important

**Comment by najlepsiwebdesigner** [comment]
Hi! Can you please provide a test case for this problem (fiddle)? For me
personally, this never happened. I also personally dont see a need for
special z-index option - you can set it with jquery after initialization on
datepicker container element. No component is perfect and suitable z-index
value depends heavily on the rest of the html and css used, we should
 check if it is common problem, or just a problem with your template.
Thanks!


Ing. Peter Beňo
--------------------------------
Web development & computer vision & robotics
http://peterbeno.com
