### ISSUE TITLE
Add code snippets to example page

### ISSUE THREAD

**Issue by Tralapo** [najlepsiwebdesigner/foundation-datepicker#134]
Maybe it's a good idea to add actual code-snippets to your example page, instead of only how it looks like at the end. For example how jQuery does that with 'view source': https://jqueryui.com/datepicker/

I had a hard time making it work, because I'm not a JavaScript star and didn't know what code I had to place where to make it work. A snippet like that would help a lot.

**Comment by najlepsiwebdesigner** [comment]
Fixed in latest release, 1.5.2
