### ISSUE TITLE
Attach datepicker to dinamic elements

### ISSUE THREAD

**Issue by leomendizabal** [najlepsiwebdesigner/foundation-datepicker#135]
Hi!

I'm trying to attach the fdatepicker to dinamic elements but It does not work yet. Please, could you give me some ideas? 

Thanks!

**Comment by najlepsiwebdesigner** [comment]
Just create element dynamically and then initialize the datepicker. Closing, not an issue.

**Comment by kisslk** [comment]
Hi!
 I'm trying create element dynamically and then initialize the datepicker. like this:
`html="<input class='importProdYM'/>";
$("#otherElement").append(html);
$(".importProdYM").fdatepicker({
        format:'yyyymm',
        dateFormat:'yy-mm',
        startView:'year',
        minView:'year'
    });`
but it doesn't work yet.
Please, could you give me some ideas?

Thanks!
