### ISSUE TITLE
Using foundation-datepicker for a standalone calendar

### ISSUE THREAD

**Issue by marks** [najlepsiwebdesigner/foundation-datepicker#14]
Great job! Wondering if you have any pointers on how to use this repo for a standalone calendar that appears w/o input boxes.

Mark

**Comment by najlepsiwebdesigner** [comment]
As satandalone calendar, I'm using https://github.com/Serhioromano/bootstrap-calendar (http://bootstrap-calendar.azurewebsites.net) with great success. It's not compatible with foundation right out of the box, but you can restyle it quite easily.
