### ISSUE TITLE
Dependent pickers + select current date

### ISSUE THREAD

**Issue by khilley** [najlepsiwebdesigner/foundation-datepicker#140]
From the [example ](http://foundation-datepicker.peterbeno.com/example.html) provided and in my implementation, it appears that selecting the current date is not an option with the Dependent pickers. At least with the default implementation. Is there a way to modify a setting somewhere to allow current date to be selected for one or both fields? Hoping to use this for an events website, where the current date is often what the visitor searches for.

**Comment by khilley** [comment]
Located where in the JavaScript to modify this. If anyone else is looking, you change the following line:

_return date.valueOf() <= now.valueOf() ? 'disabled' : '';
_
_return date.valueOf() < now.valueOf() ? 'disabled' : '';_

**Comment by devshinh** [comment]
Even if instructions are followed as per comment it does not help. Todays date remains disabled.
