### ISSUE TITLE
Language support not provided in 2015 version of foundation-datepicker.js

### ISSUE THREAD

**Issue by karthi-developer** [najlepsiwebdesigner/foundation-datepicker#144]
Hi,
In 2013 version various languages were supported. But in the newer version only English language is supported. We expect it to support other languages too. (Ex: French)

**Comment by najlepsiwebdesigner** [comment]
really? what about checking the lastest release? https://github.com/najlepsiwebdesigner/foundation-datepicker/tree/master/js/locales please read documentation before opening new issues!
