### ISSUE TITLE
Time picker not displaying

### ISSUE THREAD

**Issue by AlbertKamau** [najlepsiwebdesigner/foundation-datepicker#150]
The datepicker is functioning ok but the user does not get the option to select time . The code for the input is as below
`<input type="text" class="span2" name="txt_start_time" value="<?php echo Date("Y-m-d H:i") ?>" id="startTime" >`
The js code is as below
`$(function(){
        $('#startTime').fdatepicker({
                format: 'yyyy-mm-dd hh:ii',
		disableDblClickSelection: true,
		pickTime: true

	});
    });`
Am using foundation 5 and have linked all the relevant files.

**Comment by najlepsiwebdesigner** [comment]
hi! I tested your code in example page and it is working correctly. Check the browser console window, double check all included dependancies. Use current version.
