### ISSUE TITLE
Validation on input fileld

### ISSUE THREAD

**Issue by Boguslavovna** [najlepsiwebdesigner/foundation-datepicker#153]
If user enter an invalid date in the input control that is connected to datepicker (e.g. 2016/03/50), datepicker ignore this wrong value and set 2016/04/21 to this field (50th of March).
This behavior could confuse the user. It's better to set validation on input and highlight invalid date with corresponding css (something like alert).

**Comment by najlepsiwebdesigner** [comment]
Hello, good idea, I will implement this in the new big release.
