### ISSUE TITLE
Foundation Icons and Font Awesome are conflicting

### ISSUE THREAD

**Issue by clarasantana** [najlepsiwebdesigner/foundation-datepicker#170]
Hi, I saw the issue #113 and even though the proposed solution works just fine, for those who are getting this lib via Bower or NPM, it doesn't work for a lot of reasons. There's any idea on how to solve this conflict without importing the lib or overwriting stylesheet?

**Comment by najlepsiwebdesigner** [comment]
The datepicker supports leftArrow and rightArrow options, look here:
https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/master/js/foundation-datepicker.js#L45
