### ISSUE TITLE
How to clear(delete)  datime in readonly input?

### ISSUE THREAD

**Issue by ZdenekPNJ** [najlepsiwebdesigner/foundation-datepicker#175]
Hi, 
I´m trying to set how to clear(delete) date time in readonly input to 0000-00-00 or empty, when user will don´t want to fill input (etc. EndDateTime).

Thanx for your advice.

**Comment by najlepsiwebdesigner** [comment]
this is not an issue of this datepicker, use google or stackoverflow, you can get the answer is 5 minutes
