### ISSUE TITLE
TypeError: $(...).fdatepicker is not a function

### ISSUE THREAD

**Issue by gkaran** [najlepsiwebdesigner/foundation-datepicker#18]
I'm new to the RoR world and ruby as well so what I might ask is stupid. What I want to  do is to use the foundation-datepicker but I get 

> TypeError: $(...).fdatepicker is not a function

error and the calendar does not appear as it is obvious.

My application.js file has the following:

> //= require jquery
> //= require jquery_ujs
> //= require foundation
> //= require foundation-datetimepicker
> //= require turbolinks
> //= require_tree .
> $(function(){ $(document).foundation(); });
> $(function(){ $('#user_birthday').fdatepicker(); });

and I have also added 

> @import 'foundation-datetimepicker';

in the foundation_and_overrides.scss file.

Is there any conflict that I don't get? Maybe with jquery?

**Comment by dvodvo** [comment]
This issue is closed for yonks now, although it has reappeared for me just now, rails 6.1 with webpacker.
```
TypeError: $(...).fdatepicker is not a function
```
It appears that turbolinks is a culprit:
```
<%= javascript_tag do %>
document.addEventListener("turbolinks:load", function() {
	$('#user_date_of_birth').fdatepicker({
[....]
<% end %>

```
loads the script for proper execution.
