### ISSUE TITLE
webpack can not found module

### ISSUE THREAD

**Issue by caucas** [najlepsiwebdesigner/foundation-datepicker#180]
Webpack error: Module not found: Error: Cannot resolve module 'foundation-datepicker'.

The 'package.json' file does not have a 'main' property. When I added it by myself, webpack would start successfully.

{
...
  "main": "js/foundation-datepicker.js",
...
}

**Comment by pmackay** [comment]
I see there has been a [fix](https://github.com/najlepsiwebdesigner/foundation-datepicker/commit/499e2dc5ca394a85c5c23b27eaefbff351c5c1e4) for this submitted - any chance of a release soon so it can be included? I've found the same problem using browserify.

**Comment by wrburgess** [comment]
We are in the same boat with this issue

**Comment by angeleah** [comment]
Is this going to get pulled in? We have the same problem.

**Comment by najlepsiwebdesigner** [comment]
Sorry guys, I was not paying much attention to this project in recent months. It was pulled in, but not released. Check out 1.5.6
