### ISSUE TITLE
Date selected vs date broadcast on change is different

### ISSUE THREAD

**Issue by mryarbles** [najlepsiwebdesigner/foundation-datepicker#183]
I have datepicker set up like this:
 
```
let initDate: Date = moment(this._data.desiredCloseDate).toDate();
let opts = {
      daysOfWeekDisabled: "0,6",
      initialDate: initDate,
      format: "yyyy-mm-dd",
      isInline: true,
      autoclose:false
    };

    picker$.fdatepicker(opts);
    picker$.on("changeDate",(e) => {
      console.log("date was changed:", e);
    });
```

If you look at console after selecting 10/27/16 the event is:

```
{ type: "changeDate", date: Wed Oct 26 2016 17:00:00 GMT-0700 (Pacific Daylight Time) ...
```
Notice date is day behind for some reason.

**Comment by mryarbles** [comment]
Maybe this will help someone else. Problem was date returned is in UTC

Using momentjs...

picker$.on("changeDate",(e) => {
      console.log("date was changed:", e);
      let m: Moment = moment.utc(e.date);
      let dateString = m.format("YYYY-MM-DD");
     // dateString is  correct.
    });

**Comment by jkibble** [comment]
I'm curious why this was closed, it's obviously a bug?

I'm running into the same problem where the changeDate event has the offset already applied but tells moment that is in MDT timezone
