### ISSUE TITLE
Icon options not working

### ISSUE THREAD

**Issue by ipsips** [najlepsiwebdesigner/foundation-datepicker#185]
The icon options (`leftArrow`, `rightArrow`, `closeIcon`) are not working while they're mentioned in the documentation (at http://foundation-datepicker.peterbeno.com/example.html#iconfont-example)

I can see these options are supported in the source code on github:
https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/master/js/foundation-datepicker.js#L45-L47

but these lines are not in the source installed via npm/bower (ver 1.5.3)

![screen shot 2016-10-08 at 18 44 54](https://cloud.githubusercontent.com/assets/1770542/19214275/8b08de68-8d87-11e6-973e-1af222a88928.png)

**Comment by najlepsiwebdesigner** [comment]
Hi! I've updated the example page and the package to new version 1.5.5. Please update to this version and it should be fixed.

**Comment by ipsips** [comment]
👍
