### ISSUE TITLE
undefined date on load

### ISSUE THREAD

**Issue by dexster** [najlepsiwebdesigner/foundation-datepicker#188]
In the update function in 1.5.5 date.length is required on this line below but throws an error when none of the conditions directly above are met and the date is still undefined when it hits this line.

https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/1628b7740559dbba07b81910d8b7924c22f3c3a1/js/foundation-datepicker.js#L430

**Comment by najlepsiwebdesigner** [comment]
Hi! Please can you provide more information on use case when this happens? Can you produce this error on example page? http://foundation-datepicker.peterbeno.com/example.html Thanks!

**Comment by dexster** [comment]
If I use the "No inputs" example and remove the "data-date" attribute from the <a> tag the error occurs.

**Comment by najlepsiwebdesigner** [comment]
thanks!

**Comment by tristanwellz** [comment]
I'm also running into this issue. The logic starting on line 430 does not accept the use case of date still being undefined. This is a fatal error, will open up a PR for a fix.

**Comment by tristanwellz** [comment]
Howdy! I need my pr to be merged for this bug to be fixed in the latest version!! :)
