### ISSUE TITLE
Need an API to completely "null" out a date

### ISSUE THREAD

**Issue by prodigitalson** [najlepsiwebdesigner/foundation-datepicker#205]
There is no clear method like `clear` and doing `update('')` or `update(null)` result in using the initial date or `now` it seems. I was implementing Dependent pickers but the i need the "to"/"end" date to only have a value given that my "type" (a select field) is a certain value, otherwise I need to null it out. (I also tried just nulling the form field with `$('#myfield').val('')`)

**Comment by prodigitalson** [comment]
Non issue. must have been a JS compilation error. Using `$('#myfield').val('')` seems to work.

**Comment by difster** [comment]
Hey Ant! This is Difster from back in Tribe days. I logged in Yahoo messenger after years of neglect, saw your name on my list and thought I'd look you up. FYI - I'm also a programmer now after years of doing IT. Drop me a line: Larry.Diffey@gmail.com I'm pretty easy to find on FB too.
