### ISSUE TITLE
NPM version update to 1.5.6

### ISSUE THREAD

**Issue by XmlmXmlmX** [najlepsiwebdesigner/foundation-datepicker#207]
On [npmjs.com](https://www.npmjs.com/package/foundation-datepicker) the latest version is 1.5.5.

Is it possible to publish the new version?

**UPDATE:**
Same for [cdnjs.com](https://cdnjs.cloudflare.com/ajax/libs/foundation-datepicker/1.5.6/js/foundation-datepicker.min.js)

**Comment by najlepsiwebdesigner** [comment]
Hello, NPM package has been updated, thanks for report.

**Comment by XmlmXmlmX** [comment]
nice, thx
