### ISSUE TITLE
'999999-1-1' causes script to timeout

### ISSUE THREAD

**Issue by dsandstrom** [najlepsiwebdesigner/foundation-datepicker#47]
Linux - Chromium

I have a text field for the date picker on my form. I was seeing what happens when I *manually* enter a large year and I found out that I get an infinite loop after adding a year with six 9's.  There is no issue with your script disabled.   I can't figure out what is causing the loop.

**Comment by arangas** [comment]
I'm having this issue as well when entering "13/01/205555" on my site. The script is looping for a very long time between [this](https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/master/js/foundation-datepicker.js#L1183) and [this](https://github.com/najlepsiwebdesigner/foundation-datepicker/blob/master/js/foundation-datepicker.js#L1184). Maybe a sanity check of crazy day/month/year inputs is required before it tries to actually process them?

**Comment by adrianpillinger** [comment]
This is failing for me within the following function:

```
m: function(d, v) {
                        v -= 1;
                        while (v < 0) v += 12;
                        v %= 12;
                        d.setUTCMonth(v);
                        while (d.getUTCMonth() != v)
                            d.setUTCDate(d.getUTCDate() - 1);
                        return d;
                    },
```

d is an InvalidDate, so the while loop runs forever.

**Comment by adrianpillinger** [comment]
Simple solution

<input ..... maxlength="10"/>
