### ISSUE TITLE
How can I disable specific dates within the checkin/checkout example?

### ISSUE THREAD

**Issue by digitalredefned** [najlepsiwebdesigner/foundation-datepicker#75]
Hi - 

I'm trying to figure out how I can disable specific dates in the calendar and not just past dates.  I want to be able to block out dates that are already booked based on an array of dates I return.  The looping part I'm not having a problem with but just disabling a specific date I"m struggling with.

Thanks,
Jim

**Comment by najlepsiwebdesigner** [comment]
Hi,

you can use disabled documentation example as resource for your
implementation.
http://foundation-datepicker.peterbeno.com/example.html

It looks like onRender method gets currently rendered date and returns
classname for rendered element, so you can just change condition inside
this function


Ing. Peter Beňo
--------------------------------
Web development & computer vision
http://about.me/peterbeno

**Comment by digitalredefned** [comment]
Thanks for the follow up - That got me in the right direction.

**Comment by Imaginarydesign** [comment]
I know this is a closed issue but may be helpful for someone looking for a solution to this.
That's how I've solved it:

    `// Unavailable dates
    var unavailableDates = ["22/12/2016", "24/12/2016", "26/12/2016"];
    // Init Foundation Datepicker
    $(".fdatepicker").fdatepicker({
      format: 'dd/mm/yyyy',
      // Disable past dates and unavailable dates
      onRender: function (date) {
        var dmy = date.getDate() + "/" + (date.getMonth() + 1) + "/" + date.getFullYear();
        if ($.inArray(dmy, unavailableDates) != -1) {
          return 'disabled';
        }
        // if passed date or booked date return disabled class
        if (date.valueOf() < now.valueOf() ? 'disabled' : '') {
          return 'disabled';
        }
      }
    });`

**Comment by vishal9966** [comment]
code for disable one week dates from selected date
 var dateRange = [], newDate, enddate;
            var nowTemp = new Date();
            var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
            var checkin = $('#startdate').fdatepicker({
                onRender: function (date) {
                    return date.valueOf() < now.valueOf() ? 'disabled' : '';
                }
            }).on('changeDate', function (ev) {
              
                     newDate = new Date(ev.date)
                    enddate = newDate.setDate(newDate.getDate() + 7);
                    for (var d = new Date(ev.date) ; d <= new Date(enddate) ; d.setDate(d.getDate() + 1)) {
                        var mon = ev.date.getMonth()+1;
                        dateRange.push(d.getFullYear() + "-" + mon + "-" + d.getDate());
                    }            
                checkin.hide();
                $('#enddate')[0].focus();
                              
            }).data('datepicker');
 $('#enddate').fdatepicker({
                onRender: function (date) {
                   
                    var dateString = date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate();
                  
                  
                    if ($.inArray(dateString, dateRange)!= -1) {
                        return 'disabled';
                    }
                  
                }
            });
