### ISSUE TITLE
No support for chaging year.

### ISSUE THREAD

**Issue by sagaraspl** [najlepsiwebdesigner/foundation-datepicker#79]
It seems that there is no support for changing year in foundation date-picker.

This is basic functionality and it should be present. It is really irritating for user to go from current month to next 3 to 4 years.

**Comment by najlepsiwebdesigner** [comment]
Just click here
[image: Inline image 1]


Ing. Peter Beňo
--------------------------------
Web development & computer vision
http://about.me/peterbeno
