### ISSUE TITLE
Next/Previous month arrows missing

### ISSUE THREAD

**Issue by timscott** [najlepsiwebdesigner/foundation-datepicker#8]
I'm seeing that the next and previous arrows are missing.  On your demo site, the chevrons depend on `font-awesome.css`.  Does this plugin have an undocumented dependency on font-awesome?

**Comment by wangthony** [comment]
In case anyone wants to fix this without Font Awesome, just use this CSS:

```
.fa-chevron-left::before {
  content: "<";
}

.fa-chevron-right::before {
  content: ">";
}

i.fa-chevron-left::before, i.fa-chevron-right::before {
  font-style: normal !important; // override wrapping <i>
}

```
