### ISSUE TITLE
Very difficult for user to chage the year

### ISSUE THREAD

**Issue by sagaraspl** [najlepsiwebdesigner/foundation-datepicker#80]
Hi It seems that foundation datepicker is providing changing the year feature but it is very difficult for user to identify from where he/she can change the year.

So it seems that it is not user friendly interface. Instead there should be like following:

<< <      March 2015        >  >>

Where double << is for year change and < is for month change. So that navigation is easy for user.

**Comment by najlepsiwebdesigner** [comment]
No, thanks
