### ISSUE TITLE
Click input twice problem

### ISSUE THREAD

**Issue by sdemircom** [najlepsiwebdesigner/foundation-datepicker#88]
If I click input twice, the datepicker is hide. But then click again input, the datepicker dont show until click outside from input then click again input.

**Comment by rsagi** [comment]
Even Im stuck with this issue... Looking for a way to resolve this as it has to be done in 3 days for me..

**Comment by najlepsiwebdesigner** [comment]
Ok, so here is the explanation:

You are talking about doubleclick, which selects the text inside the input. You have to click somewhere else to unfocus the text, then picker works, as you describe.
