### ISSUE TITLE
Working on Mobile?

### ISSUE THREAD

**Issue by bonjoh** [najlepsiwebdesigner/foundation-datepicker#92]
Hi, I don't have datepicker working on Chrome on my Nexus 5 Android device. Is it inherently not supported on mobile browsers, or did I miss something?

It's working flawlessly on my desktop browsers.

**Comment by najlepsiwebdesigner** [comment]
I tested it on my iPhone and it doesnt work either, this should be fixed

**Comment by adammizrahi** [comment]
Zurb without mobile support?  That doesnt make much sense.

**Comment by mgntrn** [comment]
Any solution yet? Same problem here.

**Comment by najlepsiwebdesigner** [comment]
Hi guys!

I dont know why it havent worked recently but today everything works fine. I tested it on iOS simulator with multiple devices and with my iPhone and everything is OK.

I also tested it with recent motorola Android phone and it works almost correctly except this:

- in google chrome, clicking on input pops datepicker up but also opens android keyboard. If you close the keyboard, everything works fine.
- in built-in browser it is the same except little longer loading times.

So to have get it to work completely as designed we have to update the code to cope with built-in keyboard (hide it). However when we do this, user will not be able to fill the field manually. So my proposal is to let it be as-it-is.

Can you please post more details on devices you are using and describe the issues you have?

Thank you
