### ISSUE TITLE
How do I remove datepicker?

### ISSUE THREAD

**Issue by Khrystyna** [najlepsiwebdesigner/foundation-datepicker#96]
Hi! 

Could you please suggest how to remove properly datepicker? Is there any method for that?

**Comment by najlepsiwebdesigner** [comment]
Hi! Right now we dont have such a method, but I shouldn't be big problem to do it. Why do you need it? Do you need it for all the instances at once of for specific ones? Thanks

**Comment by najlepsiwebdesigner** [comment]
You can do it, just call remove method of fdatepicker :)

```
$('#dp1').fdatepicker('remove');
```

**Comment by Khrystyna** [comment]
Thanks! :)
