### ISSUE TITLE
Struggling to install foundation datepicker via bower

### ISSUE THREAD

**Issue by danny-faith** [najlepsiwebdesigner/foundation-datepicker#98]
Hi guys,

I have FoundationPress installed/running on my local machine and am using grunt to compile the scss/css. I have just run the following command * **bower install foundation-datepicker** * in the terminal (Mac) and everything seemed to run fine. The Foundation Datepicker files have been placed in the 'mytheme/bower_components/' directory. 

However I don't think the files are being included/referenced in the DOM. I can see in the README.md file that it says something about * **grunt build** *. But I'm not sure in what directory I'm sopposed to run that command in so I did it in my theme directory and the files still don't appear in the DOM.

Can anyone tell me what I should after the * **bower install foundation-datepicker** * command please?

Thank you very much.

Daniel.

**Comment by najlepsiwebdesigner** [comment]
Hi! 

Installing via bower or npm just copies the files to components directories, you still have to link them into you project manually.

Check out the readme section "manual installation", continue from step 3 (manualy include source files from step 2 in your DOM).
https://github.com/najlepsiwebdesigner/foundation-datepicker#manual-installation

Building is completely different thing - it just minifies files, so you have also *.min.js and *.min.css files available. 

I hope I helped!

**Comment by danny-faith** [comment]
Hi,

Thanks very much for your quick help. I get it now. I thought bower or grunt would do some of that. Now I think about it, how/why would grunt or bower enqueue the scripts for me.

Thanks,

Daniel.
